schema_version = "1.0.0"

id = "poser_tools"
version = "1.0.0"
name = "Poser Tools"
tagline = "A set of tools to make working with Poser figures easier"
maintainer = "Jess Green <jgreen@psy-dreamer.com>"
type = "add-on"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Tools"]

blender_version_min = "4.4.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2025 Jess Green",
]

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  "docs/",
  ".*",
  "*.pot",
  "*.po",
  "*.zip",
  "*.blend",
  "*.blend[0123456789]",
  "*.md",
]